config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "corona#home"

  namespace :corona do
    get :countries_list
    get :countries_stats
    get :country_time_series
    get :country
    get :global_time_series
    get :state_stats
  end
end

app/models/concerns/api/bing_client.rb
module Api
  class BingClient < Client

    def country_stats
      fetch_cached("#{self.class.name}/#{__method__}") { get _base_url }
    end

    private

    def _base_url
      "https://bing.com/covid/data"
    end
  end
end

app/models/concerns/api/client.rb
module Api
  class Client
    include ::Cacheable

    def initialize
      @conn = Faraday.new do |conn|
        conn.request :json
        conn.request :url_encoded
        conn.response :json
        conn.response :logger
        conn.adapter Faraday.default_adapter
      end
    end

    def get(url)
      _parse_response(@conn.get(url))
    end

    private

    def _parse_response(response)
      body = response.body
      if body.is_a? Hash
        body.with_indifferent_access
      elsif body.is_a? Array
        body.map { |b| b.is_a?(Hash) ? b.with_indifferent_access : b }
      else
        body
      end
    end
  end
end

app/models/concerns/api/ninja_client.rb
module Api
  class NinjaClient < Client
    def country_time_series_by_country_code(code)
      fetch_cached("#{self.class.name}/#{__method__}/#{code}") do
        get("#{_base_url}/#{_version}/historical/#{code}?lastdays=all")
      end
    end

    def global_time_series
      fetch_cached("#{self.class.name}/#{__method__}") do
        get("#{_base_url}/#{_version}/historical?lastdays=all")
      end
    end

    def latest_countries_stats
      fetch_cached("#{self.class.name}/#{__method__}") do
        get("#{_base_url}/#{_version}/countries?sort=cases")
      end
    end

    def latest_country_stats_by_country_code(code)
      fetch_cached("#{self.class.name}/#{__method__}/#{code}") do
        get("#{_base_url}/#{_version}/countries/#{code}?strict=false")
      end
    end

    def latest_global_stats
      fetch_cached("#{self.class.name}/#{__method__}") do
        get("#{_base_url}/#{_version}/all")
      end
    end

    private

    def _base_url
      "https://corona.lmao.ninja"
    end

    def _version
      ENV["NINJA_VERSION"] || "v2"
    end
  end
end

app/models/concerns/cacheable.rb
module Cacheable
  def fetch_cached(key, opts = {}, &block)
    opts[:expires_in] ||= 10.minutes
    Rails.cache.fetch(key, opts, &block)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/corona_controller.rb
class CoronaController < ApplicationController
  def countries_list
    countries = present(_service.countries_list, RegionsPresenter)
    render partial: 'countries_dropdown', locals: { countries: countries, selected: params[:code] }
  end

  def countries_stats
    countries_corona_data = present(_service.latest_countries_stats, CoronaDataPresenter)
    render partial: 'country_details', locals: { countries_corona_data: countries_corona_data }
  end

  def country_time_series
    time_series = present(_service.country_time_series_by_country_code(params[:code]), TimeSeriesPresenter)
    render partial: 'time_series', locals: { time_series: time_series }
  end

  def country
    @corona_data = present(_service.latest_country_stats_by_country_code(params[:code]), CoronaDataPresenter)
  end

  def global_time_series
    time_series = present(_service.global_time_series, TimeSeriesPresenter)
    render partial: 'time_series', locals: { time_series: time_series }
  end

  def home
    @corona_data = present(_service.latest_global_stats, CoronaDataPresenter)
  end

  def state_stats
    state_corona_data = present(
      _service.latest_state_stats_by_country_code(params[:country_code]),
      CoronaDataPresenter
    )
    render partial: 'state_details', locals: { state_corona_data: state_corona_data }
  end

  private

  def _service
    @_service ||= CoronaService.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flag(country_code)
    return if country_code.blank?

    content_tag(
      :span,
      nil,
      class: "flag-icon flag-icon-#{country_code.downcase}"
    )
  end
end

app/views/corona/_countries_dropdown.html.haml
.container
  .card
    .card-body
      = select_tag('',
                  options_for_select(countries.for_select, selected&.upcase),
                  prompt: "",
                  class: "select2")

:javascript
  var argumentsFromServer = {
  returnPath: "#{corona_country_path}"
  };

  $(document).ready(function() {
    CountrySelect.init().bindEvents();
  });

app/views/corona/_country_details.html.haml
.row.mb-3
  .col-md-12.col-xl-7
    .card.mb-2
      .card-header
        Country / Other Stats
      .card-content
        = render partial: "countries_table", locals: { countries_corona_data: countries_corona_data }

  .col-md-12.col-xl-5
    .card.mb-2
      .card-header
        World Map of Cases
      .card-content
        = render partial: "map", locals: { map_data: countries_corona_data.map_data }

app/views/corona/_map.html.haml
#map-container{style: 'height:50vh;'}

:javascript
  $(document).ready(function() {
      WorldMap.initChart(JSON.parse('#{raw(map_data.to_json)}'));
  });

app/views/corona/_pie_chart.html.haml
#pie-chart-container{style: 'height:350px; width:100%'}

:javascript
  $(document).ready(function() {
      PieChart.initChart(JSON.parse('#{raw(chart_data.to_json)}'));
  });

app/views/corona/_rate_distribution.html.haml
#rate-distribution-container{style: 'height:350px; width:100%'}

:javascript
  $(document).ready(function() {
      PieChart.initChart(JSON.parse('#{raw(chart_data.to_json)}'));
  });

app/views/corona/_state_details.html.haml
.row
  .col-md-12.col-xl-7
    .card.mb-2
      .card-header
        State or Province Stats
      .card-content
        = render partial: "state_table", locals: { state_corona_data: state_corona_data }

  .col-md-12.col-xl-5
    .card.mb-2
      .card-header
        Map of Cases
      .card-content
        = render partial: "state_map", locals: { map_data: state_corona_data.map_data_for_state }

app/views/corona/_state_map.html.haml
#map-container{style: 'height:60vh;'}
:javascript
  $(document).ready(function() {
    CountryMap.initChart(JSON.parse('#{raw(map_data.to_json)}'));
  });

app/views/corona/_state_or_province_table.html.haml
%table#state-or-province-data-table.display.table.table-hover.table-dark.w-100.table-sm
  %thead
    %tr.text-white
      %th.w-12-5 State or Province
      %th Confirmed
      %th New Cases
      %th Deaths
      %th New Deaths
      %th Recovered
      %th Mortality Rate
  %tbody
    - state_or_province_corona_data.each do |item|
      %tr
        %td.text-left= item.region_data.name
        %td.text-info= item.stats.readable_confirmed
        %td.bg-info= item.stats.readable_new_confirmed
        %td.text-danger= item.stats.readable_deaths
        %td.bg-danger= item.stats.readable_new_deaths
        %td.text-success= item.stats.readable_recovered
        %td.text-white= item.stats.readable_mortality_rate

:javascript
  $(document).ready(function() {
    $('#state-or-province-data-table').DataTable({
            bInfo: false,
            order: [[1, "desc"]],
            paging: false,
            scrollCollapse: true,
            scrollY: "50vh",
            scrollX: true,
    });
  });

app/views/corona/_state_table.html.haml
%table#state-or-province-data-table.display.table.table-hover.table-dark.w-100.table-sm
  %thead
    %tr.text-white
      %th.w-12-5 State or Province
      %th Confirmed
      %th New Cases
      %th Deaths
      %th New Deaths
      %th Recovered
      %th Mortality Rate
  %tbody
    - state_corona_data.each do |item|
      %tr
        %td.text-left= item.region_data.name
        %td.text-info= item.stats.readable_confirmed
        %td.bg-info= item.stats.readable_new_confirmed
        %td.text-danger= item.stats.readable_deaths
        %td.bg-danger= item.stats.readable_new_deaths
        %td.text-success= item.stats.readable_recovered
        %td.text-white= item.stats.readable_mortality_rate

:javascript
  $(document).ready(function() {
    $('#state-or-province-data-table').DataTable({
            bInfo: false,
            order: [[1, "desc"]],
            paging: false,
            scrollCollapse: true,
            scrollY: "50vh",
            scrollX: true,
    });
  });

app/views/corona/_time_series.html.haml
.row.mb-3
  .col-xs-12.col.sm-12.col-md.mb-3
    .card
      .card-header
        Time Series
      .card-content.text-white
        = render partial: "time_series_chart", locals: { chart_data: time_series.time_series_chart_data,
                                                          selector: "time-series-counts" }

  .col-xs-12.col.sm-12.col-md.mb-3
    .card
      .card-header
        Mortality vs Recovery Rate
      .card-content.text-white
        = render partial: "time_series_chart", locals: { chart_data: time_series.mortality_vs_recovery_chart_data,
                                                          selector: "time-series-comparisons-container" }

app/views/corona/_top_stats.html.haml
.card
  .card-body
    .row
      .col-xs-12.col-sm-4.col-xl
        .card.text-center.card-info
          .card-content
            .card-body
              %span
                %h3
                  %i.fas.fa-head-side-cough
                Confirmed
              %div
                %h3= stats.readable_confirmed

      .col-xs-12.col-sm-4.col-xl
        .card.border-top-0.border-right-0.border-left-0.text-center.card-warning
          .card-content
            .card-body
              %span
                %h3
                  %i.fas.fa-hospital-user
                Critical
              %div
                %h3= stats.readable_critical

      .col-xs-12.col-sm-4.col-xl
        .card.border-top-0.border-right-0.border-left-0.text-center.card-success
          .card-content
            .card-body
              %span
                %h3
                  %i.fas.fa-running
                Recovered
              %div
                %h3= stats.readable_recovered

      .col-xs-12.col-sm-4.col-xl
        .card.border-top-0.border-right-0.border-left-0.text-center.card-primary
          .card-content
            .card-body
              %span
                %h3
                  %i.fas.fa-ambulance
                Tests
              %div
                %h3= stats.readable_tests

      .col-xs-12.col-sm-4.col-xl
        .card.border-top-0.border-right-0.border-left-0.text-center.card-danger
          .card-content
            .card-body
              %span
                %h3
                  %i.fas.fa-procedures
                Deaths
              %div
                %h3= stats.readable_deaths

      .col-xs-12.col-sm-4.col-xl
        .card.border-top-0.border-right-0.border-left-0.text-center.card-white
          .card-content
            .card-body
              %span
                %h3
                  %i.fas.fa-skull-crossbones
                Mortality
              %div
                %h3= stats.readable_mortality_rate

app/views/corona/_top_stats_mobile.html.haml
#top-stats-mobile.card
  .card-header
    Summary
    %small.float-right
      = stats.formatted_last_updated
  .card-body
    .table-responsive
      %table.table.table-dark.table-bordered.w-100
        %tbody
          %tr
            %td Confirmed
            %td.text-info= stats.readable_confirmed
            %td Critical
            %td.text-warning= stats.readable_critical
          %tr
            %td Recovered
            %td.text-success= stats.readable_recovered
            %td Tests
            %td.text-primary= stats.readable_tests
          %tr
            %td Deaths
            %td.text-danger= stats.readable_deaths
            %td Mortality
            %td.text-white= stats.readable_mortality_rate

app/views/corona/country.html.haml
.container-fluid
  .mb-3
    = render_async corona_countries_list_path(code: params[:code]) do
      = render partial: "loading_card", locals: { header: "Countries" }

  .mb-3
    .d-none.d-sm-block
      = render partial: "top_stats", locals: { stats: @corona_data.stats }
    .d-sm-none
      = render partial: "top_stats_mobile", locals: { stats: @corona_data.stats }

  - if @corona_data.region_data.state_stats?
    = render_async corona_state_stats_path(country_code: @corona_data.region_data.alpha2) do
      .row.mb-3
        .col-md-12.col-xl-7
          = render partial: "loading_card", locals: { header: "State or Province Stats" }
        .col-md-12.col-xl-5.mb-3
          = render partial: "loading_card", locals: { header: "Map of Cases" }

  .row.mb-3
    .col-xs-12.col-sm-12.col-lg-4
      .card.mb-2
        .card-header
          Rate Distribution
        .card-body
          = render partial: "rate_distribution", locals: { chart_data: @corona_data.stats.pie_chart_data }

    .col-xs-12.col-sm-12.col-lg-8
      = render_async corona_country_time_series_path(code: params[:code]) do
        .row
          .col.mb-3
            = render partial: "loading_card", locals: { header: "Time Series" }
          .col.mb-3
            = render partial: "loading_card", locals: { header: "Mortality vs Recovery Rate" }

app/views/corona/home.html.haml
.container-fluid
  .mb-3
    = render_async corona_countries_list_path do
      = render partial: "loading_card", locals: { header: "Countries" }

  .mb-3
    .d-none.d-sm-block
      = render partial: "top_stats", locals: { stats: @corona_data.stats }
    .d-sm-none
      = render partial: "top_stats_mobile", locals: { stats: @corona_data.stats }

  = render_async corona_countries_stats_path do
    .row.mb-3
      .col-md-12.col-xl-7
        = render partial: "loading_card", locals: { header: "Country / Other Stats" }
      .col-md-12.col-xl-5.mb-3
        = render partial: "loading_card", locals: { header: "World Map of Cases" }


  .row.mb-3
    .col-xs-12.col-sm-12.col-lg-4
      .card.mb-2
        .card-header
          Rate Distribution
        .card-body
          = render partial: "rate_distribution", locals: { chart_data: @corona_data.stats.pie_chart_data }

    .col-xs-12.col-sm-12.col-lg-8
      = render_async corona_global_time_series_path do
        .row
          .col.mb-3
            = render partial: "loading_card", locals: { header: "Time Series" }
          .col.mb-3
            = render partial: "loading_card", locals: { header: "Mortality vs Recovery Rate" }

app/views/layouts/_footer.html.haml
%footer.py-4.bg-dark.flex-shrink-0
  .container.text-white.text-center
    Copyright
    = link_to "https://github.com/bTspm/corona-track", target: "_blank" do
      %i.fab.fa-github
      bTspm
    = Time.now.year
    %div
      Data retrieved from
      = link_to "@NovelCOVID", "https://corona.lmao.ninja/docs/r", target: "_blank"
      = " Built with"
      = link_to("HighCharts", "https://highcharts.com", target: "_blank")

app/views/layouts/_google_analytics.html.haml
- if Rails.env.production?
  %script{async: "", src: "https://www.googletagmanager.com/gtag/js?id=#{ENV["G_ANALYTICS_CODE"]}"}
  :javascript
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', '#{ENV["G_ANALYTICS_CODE"]}');

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-md.navbar-dark.bg-dark
  .d-flex.flex-grow-1
    %a.navbar-brand.mx-auto{href: "/"} Corona Track

app/views/layouts/application.html.haml
%html
  %head
    %meta(content='text/html; charset=UTF-8' http-equiv='Content-Type')/
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}/

    %title CoronaTrack

    %script{defer: "defer", src: 'https://code.highcharts.com/stock/highstock.js'}
    %script{defer: "defer", src: "https://code.highcharts.com/maps/modules/map.js"}
    %script{defer: "defer", src: "https://code.highcharts.com/mapdata/custom/world.js"}
    %script{defer: "defer", src: "https://code.highcharts.com/mapdata/countries/in/custom/in-all-disputed.js"}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/ar/ar-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/au/au-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/at/at-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/bo/bo-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/br/br-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/ca/ca-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/cl/cl-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/cn/cn-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/co/co-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/cr/cr-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/cz/cz-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/dk/dk-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/do/do-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/ec/ec-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/sv/sv-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/fr/fr-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/ge/ge-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/de/de-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/hn/hn-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/hu/hu-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/in/in-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/id/id-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/ir/ir-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/it/it-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/jp/jp-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/mx/mx-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/nl/nl-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/no/no-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/pk/pk-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/pe/pe-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/pl/pl-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/pt/pt-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/ru/ru-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/kr/kr-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/es/es-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/se/se-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/ch/ch-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/gb/gb-all.js'}
    %script{defer: 'defer', src: 'https://code.highcharts.com/mapdata/countries/us/us-all.js'}

    %script{defer: "defer", crossorigin: "anonymous", integrity: "sha256-KzZiKy0DWYsnwMF+X1DvQngQ2/FxF7MF3Ff72XcpuPs=", src: "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js"}
    %script{crossorigin: 'anonymous', integrity: 'sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=', src: 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js'}
    %link{crossorigin:  "anonymous", href:  "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.4.6/css/flag-icon.min.css", integrity:  "sha256-YjcCvXkdRVOucibC9I4mBS41lXPrWfqY2BnpskhZPnw=", rel:  "stylesheet"}/

    %link{href: "https://cdn.datatables.net/v/bs4-4.1.1/dt-1.10.20/fh-3.1.6/r-2.2.3/datatables.min.css", rel: "stylesheet", type: "text/css"}/
    %script{defer: "defer", src: "https://cdn.datatables.net/v/bs4-4.1.1/dt-1.10.20/fh-3.1.6/r-2.2.3/datatables.min.js", type: "text/javascript"}

    %script{defer: "defer", src: 'http://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js'}
    %script{defer: "defer", src: 'https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.9.1/underscore-min.js', type: 'text/javascript'}
    %link{href: "https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css", rel: "stylesheet", integrity: "sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh", crossorigin: "anonymous"}
    %script{defer: "defer", src: "https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js", integrity: "sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6", crossorigin: "anonymous"}

    %script{defer: "defer", src: "https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.12/js/select2.min.js"}
    %link{href: "https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.12/css/select2.min.css", rel: "stylesheet"}/
    %link{crossorigin: "anonymous", href: "https://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-theme/0.1.0-beta.10/select2-bootstrap.min.css", integrity: "sha256-nbyata2PJRjImhByQzik2ot6gSHSU4Cqdz5bNYL2zcU=", rel: "stylesheet"}/

    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = render partial: 'layouts/google_analytics'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render partial: 'layouts/header'
    = yield
    = content_for :render_async
    = render partial: 'layouts/footer'